# Generated by Django 2.2.1 on 2019-09-18 19:05

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('user_id', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('inactive_date', models.CharField(max_length=500)),
                ('created_by', models.IntegerField(default=1)),
                ('created_date', models.CharField(max_length=500)),
                ('updated_by', models.IntegerField(default=1)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'meenfee_category_master',
            },
        ),
        migrations.CreateModel(
            name='ContentMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=250, null=True)),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('title_in_arabic', models.CharField(max_length=120)),
                ('description_in_arabic', models.TextField(max_length=250, null=True)),
                ('content_in_arabic', tinymce.models.HTMLField(verbose_name='Content in Arabic')),
                ('legal_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meenfee_content_master',
            },
        ),
        migrations.CreateModel(
            name='SubCategoryMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(default=1)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('user_id', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('inactive_date', models.CharField(max_length=500)),
                ('created_by', models.IntegerField(default=1)),
                ('created_date', models.CharField(max_length=500)),
                ('updated_by', models.IntegerField(default=1)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'meenfee_sub_category_master',
            },
        ),
    ]
