# Generated by Django 2.2.1 on 2019-10-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmaster',
            name='main_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentmaster',
            name='main_content_arabic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
