# Generated by Django 2.2.1 on 2019-10-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20191003_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentmaster',
            name='main_content',
        ),
        migrations.RemoveField(
            model_name='contentmaster',
            name='main_content_arabic',
        ),
    ]
